[tool.pyright]

include = [
    "*.py",
    "renpy/",
    "src/"
]

exclude = [
    "module/build/",
]

ignore = [
    "renpycoverage.py"
]

typeCheckingMode = "basic"

reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportMissingModuleSource = false
reportUnnecessaryTypeIgnoreComment = "information"
reportTypeCommentUsage = "information"

[tool.cyright]
include = [
    "*.py",
    "renpy/",
    "src/"
]

exclude = [
    "module/build/",
]

ignore = [
    "renpycoverage.py"
]

reportGeneralTypeIssues = false
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportMissingModuleSource = false



[tool.ruff]
line-length = 120

[tool.ruff.format]
preview = true
